/*This file is part of Silex - see http://projects.silexlabs.org/?/silex
Silex is © 2010-2011 Silex Labs and is released under the GPL License:
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License (GPL) as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. 
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
To read the license please visit http://www.gnu.org/copyleft/gpl.html
*/

/**
 * Typedef to anonymous type used to describe the aggregated layer seo structure for a single deeplink.
 * the aggregated layer seo structure is generated by grouping all component seo data of the corresponding layerSeoModel
 * 
 * @author	Raphael Harmel
 * @version 1.0
 * @date   2011-07-12
 */

package org.silex.core.seo;

import org.silex.core.seo.ComponentSeoLinkModel;
 
typedef LayerSeoAggregatedModel =
{
	public var title:String;
	public var deeplink:String;
	public var description:String;
	public var tags:String;
	public var htmlEquivalent:String;
	public var links:String;
	
	//public var childLayers:Array<ComponentSeoLinkModel>;
	public var subLayers:Array<ComponentSeoLinkModel>;
}
